creation_rules:
  - path_regex: .*secrets?.yaml
    encrypted_regex: ^(data|stringData)$
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age1h4trta4eg8vmtltk4xs507zzshtcd7tls2yeglczk224akqscfdq29tntf
  - path_regex: .*secretvalue.yaml
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age1h4trta4eg8vmtltk4xs507zzshtcd7tls2yeglczk224akqscfdq29tntf
  - path_regex: .*.env
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age1h4trta4eg8vmtltk4xs507zzshtcd7tls2yeglczk224akqscfdq29tntf
